### setting

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

relax_types = ['model', 'model_relax_x'] #, 'model_relax_y', 'model_relax_w']
data = '/0613_30min'
records = ['_obj', '_runtime', '_mingap', '_bestbd']

In [4]:
for relax_type in relax_types:
    for record in records:
        globals()[relax_type + record + '_df'] = pd.read_csv(relax_type + data + record + '.csv')

## 計算

In [5]:
def describe_df(relax_type, record):
    print(relax_type + record + '\n')
    return globals()[relax_type + record + '_df'].describe()

### obj_df

#### original

In [6]:
describe_df(relax_types[0], records[0])

model_obj

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,5868.426623,3372.523621,13246.313112,5123.191884,5507.266401,5487.731849,6093.532508,12876.916468,5122.030347,5363.168329,5761.268437
std,3245.358864,2006.840742,6502.866344,1841.188660,2869.940088,2707.905590,3876.708249,2481.567922,3698.257117,2829.362186,2803.486694
min,1608.157253,1206.640768,3529.058497,1695.824538,1627.616095,1786.585385,1495.338461,8574.374438,1263.642639,703.822948,1470.170962
25%,3551.688482,2261.492417,8963.585582,3622.740040,2993.495030,3591.019636,3463.177348,11545.475010,2352.258925,3999.011905,3747.434150
50%,5098.443747,3047.839263,11269.494491,5194.799453,4748.967197,4994.031446,5023.447931,13078.786241,4040.365192,4988.945551,5228.023895
75%,6563.762599,3897.159848,17610.729942,6461.719646,7767.356369,7073.184622,7828.600385,14259.283954,7899.793698,6414.600165,7551.613960
max,14506.007031,12156.325434,29876.898163,8577.408374,10962.236427,13962.977586,19406.084722,20191.247729,15667.378259,14207.394878,13602.931827

#### relax_x

In [7]:
describe_df(relax_types[1], records[0])

model_relax_x_obj

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,1094.935816,378.412563,1460.470920,327.217905,692.093962,747.276086,874.410915,415.900716,1407.549498,641.382885,813.655425
std,1544.080842,520.562790,1763.190389,503.196877,1054.238930,1134.303451,1773.034774,527.565121,1782.302217,1223.237088,1069.010552
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.122283,55.337052,44.433405,0.000000,53.007587,0.000000,75.152251,15.304948,0.000000,0.000000,13.304497
50%,422.769629,225.889364,721.201963,101.936735,263.918634,304.940939,225.286013,291.504408,613.803278,159.785240,408.195290
75%,1704.207900,448.587966,2132.553223,394.938146,757.011776,859.519949,793.586503,619.959886,2292.362664,564.826816,1394.006634
max,6214.523265,2571.474357,6128.320508,1854.105963,4217.301566,5059.239054,9257.611886,2406.647397,7345.570179,5293.080187,4482.129566

#### relax_y

In [22]:
describe_df(relax_types[2], records[0])

model_relax_y_obj

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2335.407805,1275.782008,1517.835246,1423.322260,2331.501242,1504.711811,1830.914727,4484.056669,979.653868,1399.460823,1591.094875
std,1622.105901,924.329174,2399.528220,1025.188456,1356.437723,1744.142849,1522.779261,1448.240253,863.956095,1398.837504,1850.493897
min,200.810359,308.067573,42.743965,253.262838,673.459655,78.501391,303.040953,1493.050616,70.003777,158.926997,229.675920
25%,1253.334507,662.341982,208.241679,695.098379,1462.912954,448.966237,672.920553,4057.593200,459.130517,215.470728,351.463627
50%,2144.421888,1069.045125,528.955656,1204.372339,2038.572230,883.830693,1615.799984,4290.062051,710.174413,1101.108756,640.750116
75%,3026.164901,1610.618956,968.108490,2144.741797,2964.561983,1893.766183,2064.109619,5522.203510,1443.683627,1933.943936,2245.972363
max,5781.345533,3415.791574,7396.732799,3212.850995,4757.140819,5996.781426,4988.918514,6333.856485,2816.272379,4227.658174,5219.673610

#### relax_xy

In [23]:
describe_df(relax_types[3], records[0])

model_relax_xy_obj

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,10.000000,10.000000
mean,26.675590,3.846367,86.821554,50.169696,19.198933,16.038525,0.0,16.749345,530.306670,25.946597,0.348780
std,84.355623,12.163279,164.035819,128.320317,60.712357,50.718269,0.0,36.740442,742.198445,66.083473,1.102939
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,215.143516,0.000000,0.000000
75%,0.000000,0.000000,96.982553,0.000000,0.000000,0.000000,0.0,0.000000,671.150819,0.390536,0.000000
max,266.755903,38.463667,487.431187,404.983160,191.989329,160.385248,0.0,105.277155,2258.914537,208.557689,3.487800

In [78]:
# df = pd.concat([describe_df(relax_types[0], records[0]).iloc[[1], :],
#                 describe_df(relax_types[1], records[0]).iloc[[1], :],
#                 describe_df(relax_types[2], records[0]).iloc[[1], :],
#                 describe_df(relax_types[3], records[0]).iloc[[1], :]], axis=0)

# df.plot(kind='bar', figsize=(10,8))
# plt.legend()
# plt.show()

### runtime

In [26]:
describe_df(relax_types[0], records[1])

model_runtime

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,300.023736,257.314134,241.369438,211.140007,300.030865,242.752238,257.376271,300.025195,184.893026,227.502308,240.585130
std,0.008085,91.405237,123.697543,143.128123,0.008776,120.746417,98.499144,0.009460,148.706908,121.064218,125.302999
min,300.009597,53.084996,1.118126,1.261815,300.020811,13.562123,1.442352,300.009244,1.057046,2.433718,1.208485
25%,300.018607,300.010121,300.021216,80.696063,300.024806,300.012859,300.011365,300.019890,16.266168,225.525133,300.005785
50%,300.026429,300.017675,300.024797,300.019572,300.027459,300.023052,300.021386,300.026212,300.016853,300.016603,300.019782
75%,300.026911,300.026535,300.033085,300.027180,300.037310,300.024119,300.027290,300.032442,300.027073,300.040013,300.025455
max,300.033470,300.043617,300.046952,300.044004,300.048295,300.068551,300.032734,300.037519,300.033225,300.052258,300.031880

In [27]:
describe_df(relax_types[1], records[1])

model_relax_x_runtime

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.056186,0.055070,0.047942,0.040143,0.047845,0.045439,0.044907,0.048232,0.038478,0.047123,0.041123
std,0.026285,0.026418,0.028066,0.003081,0.021943,0.018414,0.013714,0.021153,0.002191,0.015079,0.004042
min,0.037635,0.036971,0.035950,0.036491,0.038816,0.034961,0.035973,0.036174,0.035163,0.037110,0.036392
25%,0.040529,0.039349,0.038516,0.037174,0.039128,0.038150,0.037060,0.040217,0.037085,0.039192,0.038182
50%,0.043679,0.040173,0.039335,0.040294,0.040345,0.039921,0.039725,0.042265,0.038135,0.040644,0.040359
75%,0.060935,0.064168,0.040565,0.042823,0.041930,0.042822,0.040794,0.043878,0.039877,0.043626,0.043793
max,0.105597,0.102770,0.127709,0.044773,0.109749,0.097315,0.071280,0.107877,0.042436,0.076333,0.047428

In [28]:
describe_df(relax_types[2], records[1])

model_relax_y_runtime

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,220.716099,139.741792,64.431409,162.704590,283.828731,112.599637,160.824887,300.041068,16.484335,150.330451,98.636031
std,126.824542,127.106993,124.440032,147.234420,51.223653,138.566265,143.431114,0.027597,48.132538,157.791231,140.365088
min,0.739501,1.138745,0.146731,0.387572,138.043660,0.294226,0.670091,300.025135,0.141757,0.189916,0.478446
25%,144.387724,11.489119,0.235239,8.458882,300.018635,2.449013,10.693768,300.027641,0.230229,0.499893,0.923433
50%,300.013590,142.356798,1.370191,196.731626,300.026165,25.632401,186.755637,300.032827,0.817594,150.749633,8.538259
75%,300.022976,267.062774,21.041603,300.021716,300.032557,266.591058,300.025978,300.038747,2.993558,300.026955,241.457517
max,300.030726,300.037922,300.051257,300.029476,300.042477,300.031150,300.031172,300.117671,153.417348,300.027936,300.040632

In [29]:
describe_df(relax_types[3], records[1])

model_relax_xy_runtime

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.039355,0.039191,0.047608,0.043994,0.038666,0.038636,0.036363,0.044355,0.063007,0.049641,0.039256
std,0.018689,0.014343,0.026043,0.018059,0.013322,0.013655,0.003498,0.018387,0.026376,0.024724,0.013755
min,0.030891,0.032185,0.028756,0.031562,0.031636,0.030417,0.032812,0.032203,0.031445,0.029721,0.031184
25%,0.032320,0.033591,0.031579,0.033229,0.033420,0.032311,0.033479,0.034265,0.035014,0.034215,0.033728
50%,0.033475,0.034244,0.032778,0.036418,0.034608,0.034882,0.035302,0.036784,0.073717,0.035982,0.035684
75%,0.035000,0.035601,0.065048,0.040607,0.036281,0.036472,0.039371,0.039610,0.074668,0.070343,0.036709
max,0.092294,0.079429,0.100789,0.079480,0.076252,0.076662,0.042024,0.083272,0.100304,0.091681,0.077972

### mingap

In [30]:
describe_df(relax_types[0], records[2])

model_mingap

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.546938,0.402123,0.472429,0.375902,0.547418,0.426639,0.391560,0.785534,0.186385,0.303550,0.370075
std,0.121798,0.245086,0.349386,0.277615,0.132792,0.254637,0.239398,0.058737,0.191845,0.302375,0.272555
min,0.343772,0.000000,0.000000,0.000000,0.353972,0.000000,0.000657,0.707745,0.000000,0.000000,0.000000
25%,0.470246,0.291676,0.156890,0.090591,0.455856,0.316697,0.256861,0.738476,0.000000,0.000000,0.113573
50%,0.543859,0.449073,0.581980,0.442706,0.547265,0.531569,0.476277,0.787755,0.175875,0.326718,0.422724
75%,0.654367,0.580958,0.771964,0.600201,0.609511,0.560394,0.544703,0.830531,0.342935,0.575970,0.631072
max,0.719524,0.714729,0.851797,0.684715,0.810657,0.736941,0.689790,0.880954,0.502921,0.617448,0.658210

In [31]:
describe_df(relax_types[1], records[2])

model_relax_x_mingap

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
describe_df(relax_types[2], records[2])

model_relax_y_mingap

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.321001,0.155046,0.139749,0.196450,0.440112,0.168623,0.224758,0.764430,0.002056,0.237396,0.196069
std,0.295636,0.260793,0.298697,0.245476,0.235872,0.280078,0.294772,0.090776,0.003447,0.257497,0.312978
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.534084,0.000000,0.000000,0.000000
25%,0.004956,0.000000,0.000000,0.000000,0.353221,0.000000,0.000000,0.753672,0.000000,0.000000,0.000000
50%,0.350873,0.002944,0.000000,0.095548,0.515752,0.005247,0.007114,0.782423,0.000000,0.191999,0.002294
75%,0.583739,0.277283,0.000000,0.379662,0.631369,0.323316,0.504195,0.800462,0.003658,0.473976,0.476292
max,0.715382,0.713467,0.803118,0.639181,0.658827,0.759217,0.725696,0.863335,0.009934,0.597207,0.670272

In [33]:
describe_df(relax_types[3], records[2])

model_relax_xy_mingap

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### bestbd

In [34]:
describe_df(relax_types[0], records[3])

model_bestbd

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,1767.193026,1426.161303,1448.357722,1478.848447,1751.008429,1496.917994,1804.811764,1560.758120,1964.070058,1515.473124,1467.452031
std,459.313564,100.612783,719.203029,485.432841,638.170358,416.937696,505.489738,407.099824,863.523741,597.636728,557.170650
min,829.892072,1296.434446,598.370565,582.993201,678.746199,894.102697,814.437095,915.030449,1166.536611,729.378854,664.572784
25%,1581.374287,1341.557024,918.909967,1169.469518,1520.315663,1264.668214,1549.183704,1226.142356,1348.869229,1281.351803,1135.384845
50%,1738.112252,1420.868642,1360.190250,1637.592612,1542.430068,1356.254913,1838.309327,1583.592737,1719.155063,1500.229664,1433.514435
75%,2078.941408,1484.884842,1653.228502,1898.678418,1928.189661,1818.349356,2168.714990,1899.257978,2203.872539,1573.076765,1660.108809
max,2393.963908,1599.742607,2748.198575,1963.430835,2974.456625,2223.651628,2552.123401,2144.206579,3852.135446,2730.942144,2457.355286

In [35]:
describe_df(relax_types[1], records[3])

model_relax_x_bestbd

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
mean,2.942954e+01,7.494112e+00,1.082820e+02,5.680179e+01,2.370394e+01,2.439610e+01,-1.455192e-12,2.753451e+01,6.199284e+02,3.872472e+01,3.251109e+00
std,9.306438e+01,2.369846e+01,1.926067e+02,1.415749e+02,7.495845e+01,7.714725e+01,5.477142e-12,5.810337e+01,8.256978e+02,8.424964e+01,1.028091e+01
min,-7.275958e-12,-3.637979e-12,-7.275958e-12,0.000000e+00,-7.275958e-12,-7.275958e-12,-7.275958e-12,-3.637979e-12,-3.637979e-12,-7.275958e-12,-3.637979e-12
25%,-2.728484e-12,0.000000e+00,-6.366463e-12,0.000000e+00,-3.637979e-12,-2.728484e-12,-3.637979e-12,-2.728484e-12,7.275958e-12,9.094947e-13,0.000000e+00
50%,0.000000e+00,0.000000e+00,0.000000e+00,3.637979e-12,0.000000e+00,0.000000e+00,-3.637979e-12,1.818989e-12,2.961644e+02,3.637979e-12,0.000000e+00
75%,2.728484e-12,3.637979e-12,1.358293e+02,3.637979e-12,0.000000e+00,3.637979e-12,0.000000e+00,6.366463e-12,8.218292e+02,2.733243e+01,6.366463e-12
max,2.942954e+02,7.494112e+01,5.276112e+02,4.442173e+02,2.370394e+02,2.439610e+02,1.091394e-11,1.430595e+02,2.460180e+03,2.648957e+02,3.251109e+01

In [36]:
describe_df(relax_types[2], records[3])

model_relax_y_bestbd

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,1204.172757,876.748029,674.415289,934.003225,1133.655726,847.263792,1064.879376,974.178312,978.833427,762.929033,790.100260
std,415.162783,329.004598,578.496526,446.875388,473.105649,476.823406,520.619512,272.930193,864.280066,576.978604,543.476227
min,200.783744,308.067573,42.743965,250.883491,376.714127,78.501391,303.040953,599.347956,70.003777,158.926997,228.672606
25%,1068.534551,661.378033,208.241679,688.594501,829.523914,446.269314,672.920553,736.051760,457.550755,215.470728,351.463627
50%,1270.682518,946.095858,528.955656,996.883527,1143.808355,883.830693,1042.893309,968.695639,708.562509,745.885089,637.401986
75%,1451.100462,1085.530001,968.108490,1263.686878,1362.062292,1266.422128,1517.078669,1217.462701,1443.683627,1118.218512,1084.575377
max,1645.475001,1308.681188,1701.832419,1565.396677,2070.276366,1443.924872,1802.988079,1363.111728,2816.272379,1702.870888,1721.074943

In [37]:
describe_df(relax_types[3], records[3])

model_relax_xy_bestbd

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
mean,2.667559e+01,3.846367e+00,8.682155e+01,5.016970e+01,1.919893e+01,1.603852e+01,-1.455192e-12,1.674934e+01,5.303067e+02,2.594660e+01,3.487800e-01
std,8.435562e+01,1.216328e+01,1.640358e+02,1.283203e+02,6.071236e+01,5.071827e+01,5.477142e-12,3.674044e+01,7.421984e+02,6.608347e+01,1.102939e+00
min,-7.275958e-12,-3.637979e-12,-7.275958e-12,0.000000e+00,-7.275958e-12,-7.275958e-12,-7.275958e-12,-3.637979e-12,-3.637979e-12,-7.275958e-12,-3.637979e-12
25%,-2.728484e-12,0.000000e+00,-6.366463e-12,0.000000e+00,-3.637979e-12,-2.728484e-12,-3.637979e-12,-2.728484e-12,7.275958e-12,9.094947e-13,0.000000e+00
50%,0.000000e+00,0.000000e+00,0.000000e+00,3.637979e-12,0.000000e+00,0.000000e+00,-3.637979e-12,1.818989e-12,2.151435e+02,3.637979e-12,0.000000e+00
75%,2.728484e-12,3.637979e-12,9.698255e+01,3.637979e-12,0.000000e+00,3.637979e-12,0.000000e+00,6.366463e-12,6.711508e+02,3.905361e-01,6.366463e-12
max,2.667559e+02,3.846367e+01,4.874312e+02,4.049832e+02,1.919893e+02,1.603852e+02,1.091394e-11,1.052772e+02,2.258915e+03,2.085577e+02,3.487800e+00

### 30 分鐘結果 describe

#### mingap

In [34]:
print('mingap')
mingap_df.describe()

mingap

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.453436,0.317541,0.408769,0.319100,0.452179,0.358143,0.306716,0.752449,0.094987,0.257463,0.287140
std,0.162113,0.241265,0.367885,0.248894,0.167586,0.238544,0.225524,0.068302,0.145133,0.270562,0.269351
min,0.137386,0.000000,0.000000,0.000000,0.189587,0.000000,0.000657,0.669496,0.000000,0.000000,0.000000
25%,0.373446,0.081510,0.008191,0.065993,0.334531,0.191575,0.082657,0.694809,0.000000,0.000000,0.002357
50%,0.442577,0.338728,0.504633,0.340932,0.459741,0.454223,0.373902,0.752286,0.008877,0.242326,0.294943
75%,0.599522,0.508017,0.727453,0.515662,0.526582,0.480614,0.454568,0.805973,0.156944,0.508856,0.562377
max,0.655695,0.664532,0.835863,0.635057,0.768634,0.687562,0.629477,0.860297,0.444747,0.549664,0.597547

In [35]:
print('時限內找到最佳解的個數')
mingap_df.apply(pd.Series.value_counts, axis=0).iloc[0]

時限內找到最佳解的個數

benchmark           NaN
init_prod_time_L    1.0
init_prod_time_H    2.0
prod_discount_L     2.0
prod_discount_H     NaN
weight_L            1.0
weight_H            NaN
due_time_L          NaN
due_time_H          4.0
maint_len_L         4.0
maint_len_H         3.0
Name: 0.0, dtype: float64

#### runtime

In [36]:
print('runtime')
runtime_df.describe()

runtime

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,1800.028357,1441.469292,1222.373685,1261.152753,1800.038687,1442.793117,1323.413446,1800.030278,895.339255,984.872647,1226.531418
std,0.006607,714.985788,782.998845,867.673601,0.030135,753.112778,775.213687,0.014561,863.541613,866.008433,804.272222
min,1800.021563,54.659673,1.134129,1.304724,1800.015710,13.736346,1.440630,1800.006428,1.055655,2.429676,1.104842
25%,1800.024985,1677.960341,648.812439,455.671913,1800.023115,1800.018113,796.061696,1800.025827,16.527679,225.074547,517.761376
50%,1800.026020,1800.011252,1800.015741,1800.024241,1800.027437,1800.021269,1800.025721,1800.027269,852.144144,1086.365936,1800.016945
75%,1800.031272,1800.024930,1800.023742,1800.027659,1800.042082,1800.025736,1800.027302,1800.031757,1800.024709,1800.023991,1800.021797
max,1800.043544,1800.027172,1800.046159,1800.036679,1800.119986,1800.045142,1800.036568,1800.059159,1800.028020,1800.045099,1800.027292

#### obj

In [37]:
print('obj')
obj_df.describe()

obj

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,4307.149398,2774.135175,4677.859059,3052.506053,4015.732483,3350.606870,3573.266609,7527.689688,2570.288786,2858.347549,3110.909757
std,1958.606251,1223.850539,3938.558202,1860.336522,1392.995098,2274.450045,1937.443103,1958.133354,1234.988787,1952.722004,2274.235384
min,1592.029869,1393.733912,598.370565,582.993201,2361.097854,894.102697,818.769582,3942.411612,1244.902091,729.378854,664.572784
25%,2656.537841,1919.493482,1794.195934,1531.079596,2816.958029,1898.896782,1984.201917,6529.880595,1467.781657,1291.689279,1492.227351
50%,4175.298912,2617.770483,2987.456401,2903.084504,3765.672713,2646.063136,3814.764582,7713.062655,2147.432980,2682.447402,2404.594731
75%,5870.176749,3261.884498,7835.551772,4489.713924,4852.880614,4212.340882,4481.015471,8408.981422,3803.608105,3904.747600,4222.497262
max,7496.116865,5603.418641,11441.905724,6054.350652,6240.814728,8453.065091,7195.218109,10604.743905,4173.983667,6407.265364,7165.498062

### 五分鐘比較（原始 model vs. relax model）

#### mingap

In [59]:
print('mingap_5min')
mingap_df_5min.describe()

mingap_5min

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.548300,0.403260,0.473203,0.376811,0.548685,0.427562,0.392863,0.785701,0.186144,0.303369,0.371867
std,0.121228,0.245165,0.349128,0.278055,0.132318,0.254908,0.239434,0.058728,0.191711,0.302303,0.270016
min,0.346495,0.000000,0.000000,0.000000,0.356274,0.000000,0.000657,0.708487,0.000000,0.000000,0.000000
25%,0.471526,0.294855,0.158829,0.091102,0.457237,0.318362,0.260884,0.738129,0.000000,0.000000,0.128918
50%,0.545254,0.450688,0.583023,0.444338,0.548487,0.532583,0.477538,0.788275,0.175479,0.326261,0.422001
75%,0.654983,0.581833,0.772116,0.601231,0.610779,0.561379,0.545750,0.830767,0.342407,0.575778,0.630284
max,0.720742,0.715377,0.851897,0.685498,0.811104,0.737597,0.690464,0.880954,0.502848,0.617190,0.659108

In [55]:
print('時限內找到最佳解的個數')
mingap_df_5min.apply(pd.Series.value_counts, axis=0).iloc[0]

時限內找到最佳解的個數

benchmark           NaN
init_prod_time_L    1.0
init_prod_time_H    2.0
prod_discount_L     2.0
prod_discount_H     NaN
weight_L            1.0
weight_H            NaN
due_time_L          NaN
due_time_H          4.0
maint_len_L         4.0
maint_len_H         2.0
Name: 0.0, dtype: float64

In [60]:
print('mingap_relax_5min')
mingap_df_relax_5min.describe()

mingap_relax_5min

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.322316,0.156319,0.140136,0.198980,0.444657,0.169347,0.225654,0.765288,0.002056,0.238423,0.196126
std,0.296559,0.262759,0.299412,0.246834,0.235990,0.281161,0.295804,0.090495,0.003447,0.258603,0.313069
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.535590,0.000000,0.000000,0.000000
25%,0.004956,0.000000,0.000000,0.000000,0.357833,0.000000,0.000000,0.755749,0.000000,0.000000,0.000000
50%,0.353530,0.002944,0.000000,0.099128,0.519988,0.005247,0.007114,0.782634,0.000000,0.191951,0.002294
75%,0.584983,0.280691,0.000000,0.385338,0.636374,0.325483,0.506045,0.801188,0.003658,0.476895,0.476528
max,0.717612,0.718059,0.803893,0.641243,0.662951,0.761468,0.726863,0.864201,0.009934,0.598758,0.670401

In [56]:
print('時限內找到最佳解的個數')
mingap_df_relax_5min.apply(pd.Series.value_counts, axis=0).iloc[0]

時限內找到最佳解的個數

benchmark           1.0
init_prod_time_L    4.0
init_prod_time_H    8.0
prod_discount_L     4.0
prod_discount_H     1.0
weight_L            4.0
weight_H            4.0
due_time_L          NaN
due_time_H          6.0
maint_len_L         5.0
maint_len_H         4.0
Name: 0.0, dtype: float64

#### runtime

In [61]:
print('runtime_5min')
runtime_df_5min.describe()

runtime_5min

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,300.024293,257.958738,241.398177,211.170173,300.026953,242.827635,257.827900,300.021388,184.847663,227.207883,240.592379
std,0.004366,90.232947,123.620678,143.080530,0.012417,120.596291,98.061462,0.009274,148.763224,121.059342,125.310909
min,300.016261,54.391626,1.172580,1.335609,300.012530,13.934472,1.501592,300.009877,1.047669,2.388454,1.197973
25%,300.021258,300.015967,300.009542,80.803998,300.019155,300.013092,300.007151,300.015033,16.101176,224.359698,300.019059
50%,300.025215,300.024797,300.018692,300.017935,300.024433,300.026792,300.019644,300.022326,300.018234,300.016808,300.024869
75%,300.027372,300.026049,300.023389,300.027086,300.028973,300.035469,300.025366,300.024277,300.021873,300.024987,300.034260
max,300.030081,300.038726,300.042576,300.047369,300.051067,300.056784,300.041231,300.041847,300.041985,300.052859,300.052080

In [62]:
print('runtime_relax_5min')
runtime_df_relax_5min.describe()

runtime_relax_5min

,benchmark,init_prod_time_L,init_prod_time_H,prod_discount_L,prod_discount_H,weight_L,weight_H,due_time_L,due_time_H,maint_len_L,maint_len_H
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,222.622854,141.933159,64.633187,163.219173,284.439135,113.431358,162.280825,300.029506,17.071063,150.331985,98.744175
std,127.076689,127.171343,124.355469,146.913643,49.291185,138.759013,143.967353,0.017711,49.852159,157.789034,140.325417
min,0.729809,1.184852,0.155367,0.400019,144.153970,0.299408,0.722567,300.010181,0.144537,0.177639,0.517831
25%,151.141495,11.992863,0.246794,8.760345,300.012607,2.549966,11.040706,300.023624,0.239564,0.532810,0.932947
50%,300.013184,148.876539,1.424411,198.715202,300.023578,26.316457,193.459993,300.026670,0.843653,150.739645,8.565227
75%,300.023249,268.782414,22.073102,300.017728,300.028897,268.252777,300.020054,300.032715,3.098555,300.022742,241.701070
max,300.032150,300.029209,300.036215,300.028446,300.063628,300.021776,300.048871,300.073434,158.896424,300.027110,300.027218